// screens/DailyReminderScreen.js
import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import { getDayOfYear } from 'date-fns';

// --- Daily quotes from real people (serious + fun) ---
export const dailyRemindersMeta = [
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Whether you think you can, or you think you can’t. You are right.", author: "Henry Ford" },
  { text: "What you do every day matters more than what you do once in a while.", author: "Gretchen Rubin" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Will Durant" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Focus is the art of saying no.", author: "Steve Jobs" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { text: "I can and I will. Watch me.", author: "Carrie Green" },
  { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "What would you do if you weren’t afraid?", author: "Sheryl Sandberg" },
  { text: "If you want something you’ve never had, you must be willing to do something you’ve never done.", author: "Thomas Jefferson" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Make it simple, but significant.", author: "Don Draper (fictional)" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Well-behaved women seldom make history.", author: "Laurel Thatcher Ulrich" },
  { text: "If you don’t like the road you’re walking, start paving another one.", author: "Dolly Parton" },
  { text: "Be so good they can’t ignore you.", author: "Steve Martin" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama (attributed)" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "I choose to make the rest of my life the best of my life.", author: "Louise Hay" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "If you don’t risk anything, you risk even more.", author: "Erica Jong" },
  { text: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "Fortune favors the bold.", author: "Latin Proverb" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "The only way out is through.", author: "Robert Frost" },
  { text: "If you want to fly, give up everything that weighs you down.", author: "Toni Morrison" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "If it’s both terrifying and amazing, then you should definitely pursue it.", author: "Erada" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Courage starts with showing up and letting ourselves be seen.", author: "Brené Brown" },
  { text: "Habits are the compound interest of self‑improvement.", author: "James Clear" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "You don’t have to be perfect to be amazing.", author: "Unknown" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "A little progress each day adds up to big results.", author: "Unknown" },
  { text: "Start now. Get better along the way.", author: "Paul Arden" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "What is done in love is done well.", author: "Vincent van Gogh" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "If people are doubting how far you can go, go so far that you can’t hear them anymore.", author: "Michele Ruiz" },
  { text: "Go the extra mile. It’s never crowded.", author: "Wayne Dyer" },
  { text: "Screw it, let’s do it.", author: "Richard Branson" },
  { text: "If it doesn’t challenge you, it won’t change you.", author: "Fred DeVito" },
  { text: "The comeback is always stronger than the setback.", author: "Unknown" },
  { text: "She believed she could, so she did.", author: "R.S. Grey" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
  { text: "You are allowed to be both a masterpiece and a work in progress simultaneously.", author: "Sophia Bush" },
  { text: "If you want to be interesting, be interested.", author: "David Ogilvy" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "Think like a queen. A queen is not afraid to fail.", author: "Oprah Winfrey" },
  { text: "Never let a good crisis go to waste.", author: "Rahm Emanuel" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Be a voice, not an echo.", author: "Albert Einstein (attributed)" },
  { text: "If you’re the smartest person in the room, you’re in the wrong room.", author: "Marissa Mayer" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "If you don’t build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Success is getting what you want; happiness is wanting what you get.", author: "W.P. Kinsella" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Everything is figureoutable.", author: "Marie Forleo" },
  { text: "Never, never, never give up.", author: "Winston Churchill" },
  { text: "If you can’t yet do great things, do small things in a great way.", author: "Napoleon Hill" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Keep moving forward.", author: "Walt Disney" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { text: "The man on top of the mountain didn’t fall there.", author: "Vince Lombardi" },
  { text: "If you want to make everyone happy, don’t be a leader. Sell ice cream.", author: "Steve Jobs (attributed)" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Life shrinks or expands in proportion to one’s courage.", author: "Anaïs Nin" },
  { text: "If you’re offered a seat on a rocket ship, don’t ask what seat. Just get on.", author: "Sheryl Sandberg" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { text: "The most effective way to do it, is to do it.", author: "Amelia Earhart" },
  { text: "The brave may not live forever, but the cautious do not live at all.", author: "Richard Branson" },
  { text: "Perfection is the enemy of progress.", author: "Winston Churchill" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "If you don’t like something, change it. If you can’t change it, change your attitude.", author: "Maya Angelou" },
  { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "The grass is greener where you water it.", author: "Neil Barringham" },
  { text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou" },
  { text: "If you can’t stop thinking about it, don’t stop working for it.", author: "Michael Jordan (attributed)" },
  { text: "When you have a dream, you’ve got to grab it and never let go.", author: "Carol Burnett" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "If you get tired, learn to rest, not to quit.", author: "Banksy" },
  { text: "Say yes, and you’ll figure it out afterward.", author: "Tina Fey" },
  { text: "If you don’t ask, the answer is always no.", author: "Nora Roberts" },
  { text: "If you think adventure is dangerous, try routine. It is lethal.", author: "Paulo Coelho" },
  { text: "You can’t pour from an empty cup. Take care of yourself first.", author: "Unknown" },
  { text: "Work hard in silence; let success make the noise.", author: "Frank Ocean (attributed)" },
  { text: "If you obey all the rules, you miss all the fun.", author: "Katharine Hepburn" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "If it’s not a hell yes, it’s a no.", author: "Derek Sivers" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "If you want different results, do not do the same things.", author: "Albert Einstein (attributed)" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Go confidently in the direction of your dreams.", author: "Henry David Thoreau" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln (attributed)" },
  { text: "Hustle beats talent when talent doesn’t hustle.", author: "Ross Simmonds" },
  { text: "You did not come this far only to come this far.", author: "Unknown" },
  { text: "A comfort zone is a beautiful place, but nothing ever grows there.", author: "Unknown" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "What you practice grows stronger.", author: "Shauna Shapiro" },
];

// Backward‑compatible export as an array of strings "Quote - Author"
export const dailyReminders = dailyRemindersMeta.map(q => `${q.text} - ${q.author}`);

export default function DailyReminderScreen() {
  const dayIndex = (getDayOfYear(new Date()) - 1) % dailyRemindersMeta.length;
  const today = dailyRemindersMeta[dayIndex];
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.heading}>Today’s Dose of Drive</Text>
      <View style={styles.card}>
        <Text style={styles.quote}>“{today.text}”</Text>
        <Text style={styles.author}>- {today.author}</Text>
      </View>
      <Text style={styles.note}>
        Tip: You can also import { dailyRemindersMeta } to access quote + author separately.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { padding: 24 },
  heading: { fontSize: 22, fontWeight: '700', marginBottom: 16 },
  card: { backgroundColor: '#fff', borderRadius: 12, padding: 20, elevation: 3 },
  quote: { fontSize: 18, lineHeight: 26, marginBottom: 10 },
  author: { fontSize: 16, fontStyle: 'italic', opacity: 0.8 },
  note: { marginTop: 16, fontSize: 12, opacity: 0.7 },
});